services:
  - type: web
    name: btc-cloudx-bot
    env: python
    runtime: python-3.11.10
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: false
