const LANG_PACK = {
    ar: {
        // General
        nav_home: "الرئيسية",
        nav_plans: "الخطط",
        nav_hardware: "الأجهزة",
        nav_custom_plan: "خطة خاصة",
        nav_faq: "الأسئلة",
        back_text: "العودة",
        
        // Home Page
        platform_tagline: "منصة التعدين السحابي الرائدة",
        article_title: "تحسين واجهة المستخدم",
        article_content: "منصة التعدين السحابية في حاجة للمعالجة الآن حرصاً على أموالكم. نحن نعمل على تحسين الأمان والأداء لضمان أفضل تجربة استثمارية لعملائنا الكرام.",
        article_note: "💡 سيتم إشعاركم بانتهاء أعمال الصيانة قريباً",
        enter_platform_text: "تحسين واجهة المستخدم",
        maintenance_subtitle: "منصة التعدين السحابية في حاجة للمعالجة الآن",

        // Coupon System
        coupon_title: "كوبون المكافآت الشهرية",
        reveal_coupon_text: "اكشف كوبونك الآن",
        coupon_code_label: "كود الاشتراك الخاص بك:",
        rewards_title: "مكافأتك:",
        reward_amount: "مكافأة 15$ أسبوعياً",
        reward_condition: "متاح سحبها مع استلام أرباح الشهر الثالث",
        countdown_label: "انتهاء الكوبون خلال:",
        days_label: "يوم",
        hours_label: "ساعة",
        minutes_label: "دقيقة",

        // Plans Page
        plans_title: "📊 الخطط الاستثمارية المميزة",
        plan_pro_name: "العقد الاحترافي",
        plan_pro_desc: "للمستثمرين المبتدئين",
        plan_adv_name: "العقد المتقدم",
        plan_adv_desc: "للمستثمرين المتوسطين",
        plan_elite_name: "العقد النخبة المائي",
        plan_elite_desc: "للمستثمرين المحترفين",
        min_investment: "الحد الأدنى",
        mining_power: "قوة التعدين",
        used_device: "الجهاز المستخدم",
        daily_profit: "الربح اليومي",
        monthly_profit: "الربح الشهري",
        annual_profit: "الربح السنوي المتوقع",
        bonus_pro: "مكافأة نصف سنوية: $15",
        bonus_adv: "مكافأة نصف سنوية: $75",
        bonus_elite: "مكافأة نصف سنوية: $400",
        subscribe_now: "اشترك الآن",
        most_profitable: "الأكثر ربحية",

        // Hardware Page
        hardware_title: "📠 أجهزتنا للتعدين",
        s21_name: "Antminer S21 XP",
        s21_desc: "جهاز التعدين الأكثر كفاءة",
        s21_hydro_name: "Antminer S21 XP Hydro",
        s21_hydro_desc: "تقنية التبريد المائي المتقدمة",
        available: "متوفر",
        latest: "الأحدث",
        power_consumption: "استهلاك الطاقة",
        efficiency: "الكفاءة",
        tech_specs: "المواصفات التقنية",
        algorithm: "الخوارزمية:",
        op_temp: "درجة حرارة التشغيل:",
        dimensions: "الأبعاد:",
        cooling_system: "نظام التبريد:",
        book_now: "احجز جهازك الآن",

        // Custom Plan Page
        custom_plan_title: "💡 صمّم خطتك الاستثمارية",
        amount_label: "1. حدد مبلغ الاستثمار (بالدولار)",
        amount_placeholder: "الحد الأدنى 200 دولار",
        duration_label: "2. حدد مدة العقد (سنوات)",
        year_one: "سنة",
        year_two: "سنتان",
        year_three: "3 سنوات",
        year_unit: "سنة",
        calculate_button: "احسب الخطة",
        results_title: "نتائج خطتك الاستثمارية",
        investment_amount_label: "مبلغ الاستثمار",
        contract_duration_label: "مدة العقد",
        monthly_profit_label: "الربح الشهري",
        total_profit_label: "إجمالي الأرباح",
        roi_label: "العائد على الاستثمار",
        confirm_plan_btn: "تأكيد الخطة والاشتراك",
        modify_plan_btn: "تعديل الخطة",

        // FAQ Page
        faq_title: "❓ أسئلة شائعة",
        faq_data: [
            { q: 'ما هو التعدين السحابي؟', a: 'التعدين السحابي هو عملية تعدين العملات المشفرة باستخدام قوة حاسوبية مستأجرة من مراكز بيانات بعيدة. بدلاً من شراء وصيانة أجهزة التعدين بنفسك، يمكنك استئجار قوة التعدين من شركات متخصصة والحصول على حصتك من الأرباح.' },
            { q: 'كيف أبدأ الاستثمار؟', a: 'اختر إحدى الخطط الجاهزة أو صمم خطتك الخاصة، ثم تواصل معنا عبر البوت لتأكيد الاشتراك والدفع وبدء تحقيق الأرباح.' },
            { q: 'ما هي طرق الدفع المتاحة؟', a: 'نقبل الدفع عبر العملات الرقمية مثل Bitcoin و USDT، بالإضافة إلى التحويلات البنكية للمبالغ الكبيرة.' },
            { q: 'متى أحصل على أرباحي؟', a: 'تُحسب الأرباح يوميًا وتضاف إلى حسابك، ويمكنك طلب سحبها بشكل شهري.' },
            { q: 'هل الاستثمار آمن؟', a: 'نحن نستخدم أحدث تقنيات الأمان ونعمل كشركة مرخصة لضمان حماية استثماراتك. ومع ذلك، يجب أن تكون على دراية بأن أسواق العملات الرقمية متقلبة وتنطوي على مخاطر.' }
        ]
    },
    en: {
        nav_home: "Home",
        nav_plans: "Plans",
        nav_hardware: "Hardware",
        nav_custom_plan: "Custom",
        nav_faq: "FAQ",
        back_text: "Back",
        platform_tagline: "The Leading Cloud Mining Platform",
        article_title: "User Interface Upgrade",
        article_content: "The cloud mining platform is currently undergoing maintenance to secure your funds. We are improving security and performance to ensure the best investment experience.",
        article_note: "💡 You will be notified soon when maintenance is complete.",
        enter_platform_text: "UI Upgrade in Progress",
        maintenance_subtitle: "Platform is currently under maintenance",
        coupon_title: "Monthly Bonus Coupon",
        reveal_coupon_text: "Reveal Your Coupon",
        coupon_code_label: "Your Subscription Code:",
        rewards_title: "Your Reward:",
        reward_amount: "$15 Weekly Reward",
        reward_condition: "Withdrawable with 3rd month's profit",
        countdown_label: "Coupon Expires In:",
        days_label: "Days",
        hours_label: "Hours",
        minutes_label: "Mins",
        plans_title: "📊 Featured Investment Plans",
        plan_pro_name: "Pro Contract",
        plan_pro_desc: "For beginner investors",
        plan_adv_name: "Advanced Contract",
        plan_adv_desc: "For intermediate investors",
        plan_elite_name: "Elite Hydro Contract",
        plan_elite_desc: "For professional investors",
        min_investment: "Minimum",
        mining_power: "Mining Power",
        used_device: "Device Used",
        daily_profit: "Daily Profit",
        monthly_profit: "Monthly Profit",
        annual_profit: "Est. Annual Profit",
        bonus_pro: "Semi-annual bonus: $15",
        bonus_adv: "Semi-annual bonus: $75",
        bonus_elite: "Semi-annual bonus: $400",
        subscribe_now: "Subscribe Now",
        most_profitable: "Most Profitable",
        hardware_title: "📠 Our Mining Hardware",
        s21_name: "Antminer S21 XP",
        s21_desc: "The most efficient miner",
        s21_hydro_name: "Antminer S21 XP Hydro",
        s21_hydro_desc: "Advanced water-cooling tech",
        available: "Available",
        latest: "Latest",
        power_consumption: "Power Consume",
        efficiency: "Efficiency",
        tech_specs: "Technical Specs",
        algorithm: "Algorithm:",
        op_temp: "Operating Temp:",
        dimensions: "Dimensions:",
        cooling_system: "Cooling:",
        book_now: "Book Your Device",
        custom_plan_title: "💡 Design Your Plan",
        amount_label: "1. Set Investment Amount (USD)",
        amount_placeholder: "Minimum $200",
        duration_label: "2. Set Contract Duration (Years)",
        year_one: "1 Year",
        year_two: "2 Years",
        year_three: "3 Years",
        year_unit: "Year",
        calculate_button: "Calculate Plan",
        results_title: "Your Investment Plan Results",
        investment_amount_label: "Investment",
        contract_duration_label: "Duration",
        monthly_profit_label: "Monthly Profit",
        total_profit_label: "Total Profit",
        roi_label: "Return on Investment",
        confirm_plan_btn: "Confirm and Subscribe",
        modify_plan_btn: "Modify Plan",
        faq_title: "❓ FAQ",
        faq_data: [
            { q: 'What is cloud mining?', a: 'Cloud mining is the process of mining cryptocurrencies using rented computing power from remote data centers. Instead of buying and maintaining your own mining hardware, you can rent hashing power and get a share of the profits.' },
            { q: 'How do I start?', a: 'Choose one of the ready-made plans or design your own, then contact us via the bot to confirm your subscription, make the payment, and start earning.' },
            { q: 'What are the payment methods?', a: 'We accept payments via cryptocurrencies like Bitcoin and USDT, as well as bank transfers for large amounts.' },
            { q: 'When do I get my profits?', a: 'Profits are calculated daily and added to your account. You can request a withdrawal on a monthly basis.' },
            { q: 'Is the investment secure?', a: 'We use the latest security technologies and operate as a licensed company to protect your investments. However, be aware that cryptocurrency markets are volatile and involve risks.' }
        ]
    },
    zh: {
        nav_home: "主页",
        nav_plans: "计划",
        nav_hardware: "硬件",
        nav_custom_plan: "定制",
        nav_faq: "常问问题",
        back_text: "返回",
        platform_tagline: "领先的云挖矿平台",
        article_title: "用户界面升级",
        article_content: "云挖矿平台目前正在进行维护以保护您的资金。我们正在改进安全性和性能以确保最佳的投资体验。",
        article_note: "💡 维护完成后，您将很快收到通知。",
        enter_platform_text: "界面升级中",
        maintenance_subtitle: "平台正在维护中",
        coupon_title: "每月奖励优惠券",
        reveal_coupon_text: "揭示您的优惠券",
        coupon_code_label: "您的订阅代码:",
        rewards_title: "您的奖励:",
        reward_amount: "每周15美元奖励",
        reward_condition: "可与第三个月的利润一同提取",
        countdown_label: "优惠券有效期:",
        days_label: "天",
        hours_label: "小时",
        minutes_label: "分钟",
        plans_title: "📊 精选投资计划",
        plan_pro_name: "专业合约",
        plan_pro_desc: "适合初级投资者",
        plan_adv_name: "高级合约",
        plan_adv_desc: "适合中级投资者",
        plan_elite_name: "精英水冷合约",
        plan_elite_desc: "适合专业投资者",
        min_investment: "最低投资",
        mining_power: "算力",
        used_device: "使用设备",
        daily_profit: "每日利润",
        monthly_profit: "每月利润",
        annual_profit: "预计年利润",
        bonus_pro: "半年奖金: $15",
        bonus_adv: "半年奖金: $75",
        bonus_elite: "半年奖金: $400",
        faq_title: "❓ 常见问题",
        faq_data: [
            { q: '什么是云挖矿？', a: '云挖矿是使用从远程数据中心租用的计算能力来挖掘加密货币的过程。您可以租用算力并获得利润份额，而无需购买和维护自己的挖矿硬件。' },
            { q: '如何开始？', a: '选择一个现成的计划或设计您自己的计划，然后通过机器人联系我们确认您的订阅，付款并开始赚钱。' },
            { q: '有哪些付款方式？', a: '我们接受通过比特币和USDT等加密货币付款，以及大额银行转账。' },
            { q: '我什么时候能得到利润？', a: '利润每天计算并添加到您的帐户中。您可以按月申请提款。' },
            { q: '投资安全吗？', a: '我们使用最新的安全技术，并作为持牌公司运营以保护您的投资。但请注意，加密货币市场波动性大，存在风险。' }
        ]
    }
};